public class ZipStatus {
  public static final int STATUS_OK = 1,
  STATUS_FAILED_TO_OPEN_FILES = 2,
  STATUS_FAILED_TO_CLOSE_FILES = 3,
  STATUS_FAILED_TO_CREATE_ARCHIVE = 4,

  STATUS_FAILED_TO_COMPRESS = 5,

  STATUS_NON_EXISTENT_ARCHIVE = 6,
  STATUS_FAILED_TO_WRITE_ARCHIVE = 7,

  STATUS_NON_EXISTENT_FILES = 8,
  STATUS_GENERAL_FAILURE = 9,

  STATUS_FAILED_TO_DECOMPRESS= 10;

}
